---
# JBOSS Cluster
jboss_user: jboss
jboss_home: /opt/
jboss_domain_name: energisme
jboss_config_dir: /opt/jboss-eap-7.2
jboss_default_multicast_address: 230.0.0.4
jboss_domain_base_dir: /opt/jboss-eap-7.2/domain
jboss_domain_base_url: file:///opt/
jboss_domain_log_dir: /opt/jboss-eap-7.2/cluster/logs
jboss_group: energisme-server-group
jboss_messaging_cluster_password: changeme
jboss_dc: web_front_vm01
jboss_netty_port: 5445
jboss_master_ipv4: 192.168.76.76
jboss_slave1_ipv4: 192.168.76.77
#jboss_slave2_ipv4: 192.168.76.76
jboss_socket_binding_portoffset: 0
jboss_jgroups_channel: energisme-cluster
jboss_jgroups_stack: tcp
jboss_jgroups_port: 7600
jboss_domain_login_password: \,.zaxs//C3
jboss_domain_login_user: slave
cluster_nodes: "{{ groups['web_front_servers_group'] }}"
# JVM
jboss_domain_xms: Xms64m
jboss_domain_xmx: Xmx512m
# SYSLOG
jboss_rsyslog:
