all:
  hosts:
  children:
    kafka_servers_group:
      hosts:
        vm1:
    zookeeper_servers_group:
      hosts:
        vm1:
        vm2:
    nifi_servers_group:
      hosts:
        vm1:
        vm2:
    nifi_zookeeper_servers_group:
      hosts:
        vm1:
        vm2:
    nifireg_servers_group:
      hosts:
        vm3:
    web_front_servers_group:
      hosts:
        web_front_vm01:
        web_front_vm02:
    ipa:
      hosts:
      children:
        ipaserver:
          hosts:
            ipa_server_vm01:
        ipareplicas:
          hosts:
            ipa_replicas_vm01:
        ipaclients:
          hosts:
            ipa_clients_vm01:
            ipa_clients_vm02:
            ipa_clients_vm03:
          children:
            ipakeycloak_db:
              hosts:
                ipa_clients_vm03:
            ipakeycloak:
              hosts:
                ipa_clients_vm03:
            